/**
 * Mechanical checks for the design avoid-list. Each rule has a pattern, the places it applies to,
 * files it skips, and a sample that must fail and one that must pass (checked by avoid-list.test.mjs).
 */
const UI = ['apps/app/src', 'apps/landing/src', 'apps/landing/index.html', 'apps/landing/privacy', 'apps/landing/limitations', 'apps/landing/credits', 'apps/landing/offline', 'apps/landing/404.html', 'packages/ui'];
const CODE = [...UI, 'packages', 'content', 'docs', 'tools', 'ml', 'README.md', 'implementation_plan.md', 'apps/app/scripts', 'apps/landing/scripts', 'apps/landing/e2e', 'apps/app/e2e'];

export const RULES = [
  {
    id: 'em-dash',
    why: 'Em and en dashes are banned in all text. Use commas, colons or periods.',
    pattern: /[–—]/,
    scope: CODE,
    exts: ['.ts', '.tsx', '.css', '.html', '.md', '.json', '.py', '.mjs', '.ps1', '.yml', '.yaml'],
    bad: 'Care — at home',
    good: 'Care, at home',
  },
  {
    id: 'placeholders',
    why: 'No placeholder text or dead links.',
    pattern: /lorem|TODO|coming soon|example\.com|href="#"/i,
    scope: [...UI, 'content', 'apps/app/src'],
    exts: ['.ts', '.tsx', '.html', '.json'],
    bad: '<a href="#">Read</a>',
    good: '<a href="#how">Read</a>',
  },
  {
    id: 'gradient-text',
    why: 'No gradient text.',
    pattern: /bg-clip-text|text-transparent|background-clip:\s*text|text-fill-color:\s*transparent/,
    scope: UI,
    exts: ['.ts', '.tsx', '.css', '.html'],
    bad: 'class="bg-clip-text text-transparent"',
    good: 'class="text-ink"',
  },
  {
    id: 'gradients',
    why: 'No purple or blue gradients, and no gradients at all except the hero overlay.',
    pattern: /(from|via|to)-(violet|purple|indigo|blue|fuchsia|sky)-\d{2,3}|linear-gradient|radial-gradient|conic-gradient|bg-linear-|bg-gradient-|bg-radial|bg-conic/,
    scope: UI,
    exts: ['.ts', '.tsx', '.css', '.html'],
    skip: ['apps/landing/src/journey/HeroJourney.tsx', 'apps/landing/index.html'],
    bad: 'class="bg-gradient-to-r from-purple-500 to-blue-500"',
    good: 'class="bg-white"',
  },
  {
    id: 'emoji',
    why: 'No emoji in UI, content or headings.',
    pattern: /\p{Extended_Pictographic}/u,
    scope: [...UI, 'content', 'docs', 'README.md', 'implementation_plan.md'],
    exts: ['.ts', '.tsx', '.css', '.html', '.md', '.json'],
    bad: 'Well done \u{1F389}',
    good: 'Well done',
  },
  {
    id: 'inter-only-on-landing',
    why: 'Inter is a landing-page choice only. The app uses Atkinson Hyperlegible Next.',
    pattern: /\bInter\b/,
    scope: ['apps/app/src', 'packages/ui'],
    exts: ['.ts', '.tsx', '.css', '.html'],
    bad: "font-family: 'Inter'",
    good: "font-family: 'Atkinson Hyperlegible Next'",
  },
  {
    id: 'coloured-border-cards',
    why: 'No one-sided coloured borders on cards.',
    pattern: /border-[ltrb]-[248]\b|border-(left|top|right|bottom):\s*\d+px solid/,
    scope: UI,
    exts: ['.ts', '.tsx', '.css', '.html'],
    bad: 'class="border-l-4 border-green-500"',
    good: 'class="border border-line"',
  },
  {
    id: 'glass',
    why: 'Translucent blur is allowed on the nav and the pause control only.',
    pattern: /backdrop-blur|backdrop-filter/,
    scope: UI,
    exts: ['.ts', '.tsx', '.css', '.html'],
    skip: ['apps/landing/src/components/Nav.tsx', 'apps/landing/src/journey/HeroJourney.tsx'],
    bad: 'class="backdrop-blur-lg bg-white/20"',
    good: 'class="bg-white"',
  },
  {
    id: 'spacing-arbitrary',
    why: 'Spacing comes from the 4 px scale, not arbitrary values.',
    pattern: /\b(p|m|gap|space-[xy]|inset|top|left|right|bottom)[trblxy]?-\[/,
    scope: UI,
    exts: ['.ts', '.tsx', '.html'],
    bad: 'class="px-[13px]"',
    good: 'class="px-6"',
  },
  {
    id: 'eyebrow-badge',
    why: 'No small uppercase tracked labels above headlines.',
    pattern: /uppercase[^"'`]*tracking-|tracking-[^"'`]*uppercase/,
    scope: UI,
    exts: ['.tsx', '.html'],
    bad: 'class="text-xs uppercase tracking-widest"',
    good: 'class="text-sm"',
  },
  {
    id: 'shadcn-default',
    why: 'No untouched shadcn look.',
    pattern: /bg-primary text-primary-foreground|text-primary-foreground bg-primary/,
    scope: UI,
    exts: ['.ts', '.tsx', '.html'],
    bad: 'class="bg-primary text-primary-foreground"',
    good: 'class="btn btn-primary"',
  },
  {
    id: 'viewport-and-scroll',
    why: 'Use 100dvh, and never listen to scroll events.',
    pattern: /\bh-screen\b|min-h-screen|addEventListener\(\s*['"]scroll/,
    scope: UI,
    exts: ['.ts', '.tsx', '.html'],
    bad: 'class="min-h-screen"',
    good: 'class="min-h-[100dvh]"',
  },
  {
    id: 'secrets',
    why: 'No secret may appear in any file.',
    pattern: /sk-or-v1-[0-9a-f]{32,}|-----BEGIN [A-Z ]*PRIVATE KEY-----|AKIA[0-9A-Z]{16}/,
    scope: ['.'],
    exts: ['.ts', '.tsx', '.css', '.html', '.md', '.json', '.py', '.mjs', '.ps1', '.yml', '.yaml', '.env', '.txt'],
    bad: 'key sk-or-v1-0123456789abcdef0123456789abcdef',
    good: 'OPENROUTER_API_KEY',
  },
  {
    id: 'language-honesty',
    why: 'No per-language "voiceSupported" flags, and Nyishi is njz, not ny.',
    pattern: /voiceSupported|Nyishi[^\n]{0,40}['"]ny['"]/,
    scope: ['apps', 'packages', 'content'],
    exts: ['.ts', '.tsx', '.json'],
    bad: 'voiceSupported: true',
    good: 'status: "Planned"',
  },
];
